const SharedConstants = {
  partners: [
    '17a',
    'microsoft',
    'centrifuse',
    'stelizabeth',
    'sprylabs',
  ],
  Initiatives: [
    {
      name: 'Harm reduction',
      value: 1,
      icon: 'fa-heart',
      title: '',
      description: '',
      image: '',
      selected: false,
      multiplicationFactor: 0,
      equationParameter: '',
    },
    {
      name: 'Community Support',
      value: 2,
      icon: 'fa-users',
      title: '',
      description: '',
      image: '',
      selected: false,
      multiplicationFactor: 0,
      equationParameter: '',
    },
    {
      name: 'Therapy',
      value: 3,
      icon: 'fa-handshake-o ',
      title: '',
      description: '',
      image: '',
      selected: false,
      multiplicationFactor: 0,
      equationParameter: '',
    },
    {
      name: 'Treatment',
      value: 4,
      icon: 'fa-medkit',
      title: '',
      description: '',
      image: '',
      selected: false,
      multiplicationFactor: 0,
      equationParameter: '',
    },
    {
      name: 'Needle Exchanging',
      value: 5,
      icon: 'fa-exchange',
      title: '',
      description: '',
      image: '',
      selected: false,
      multiplicationFactor: 0,
      equationParameter: '',
    },
    {
      name: 'Shelters',
      value: 6,
      icon: 'fa-home',
      title: '',
      description: '',
      image: '',
      selected: false,
      multiplicationFactor: 0,
      equationParameter: '',
    },
  ],
};


export default SharedConstants;
